### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by NicoCG** [Adomix/FruitMod#3]
@Adomix,

Would be really cool if this application was docker ready 👍

**Comment by Adomix** [comment]
I am confused on what you're asking for. From what I have been reading, it should work since I run `dotnet publish -c Release -r linux-x64`

**Comment by Adomix** [comment]
@NicoCG 
Feel free to PR a docker file if you want one

**Comment by Adomix** [comment]
@NicoCG 
`cd FruitMod
docker build -t="FruitMod" .
docker run -i -t FruitMod`
I have never used Docker, I think its something like this. Sorry.
